### ISSUE TITLE
Synthmata (yes, completely off-topic, I know!)

### ISSUE THREAD

**Issue by MBYlt** [oscillatorsink/nts-1-research#1]
(Prefacing this with a preemptive apology for spamming your Github with something completely unrelated to the project in question - my humble, meager defense is that I can't find any other way of contacting you, short of Youtube comments, which send a shiver down my spine to even consider. Feel free to follow the process outlined in [this article](https://docs.github.com/en/github/managing-your-work-on-github/deleting-an-issue) to delete this completely off-topic comment)

Synthmata is *incredible*, there's really no mincing words when it comes to just how useful a tool it is. Thank you so, so much for putting the time and effort into creating it and making it so usable.

However, I'm all-too familiar with bitrot, and the thought of Synthmata vanishing one cold dark day isn't exactly a pleasant one. It's obviously not the sort of site that "website archivers" can actually archive.

I was wondering if you had given any thought to making the Synthmata source publicly available in some fashion? I can understand wanting to keep the source low-key, I can imagine it'd be really frustrating seeing it co-opted by scumbags with dollar signs in their eyes - but at the same time, something as thoughtful and downright *useful* deserves to be preserved. Maybe an offline / downloadable version, if nothing else? 

I know there's other DX7 patch editors, but the Synthmata Randomizer is absolutely unparalleled (the "this DX7 cartridge does not exist" site is cute, but it's really just variations on eight basic sounds that, imo, targets a misguided audience, those who claim to want "random" but don't actually want anything different from what they've already heard).

Arguably, the rest of Synthmata's features are covered by Dexed, but the current version of Dexed has some serious, seeeerious issues when DAW hosts try to modify its parameters - which means that using a host's Random function on Dexed is completely out of the question for the time being.

**Comment by oscillatorsink** [comment]
You're looking for: https://github.com/synthmata - my ccynthmata library is on there too for people that want to build their own similar stuff quickly (my volca drum editor is built using that library).

Also, it looks like archive.org does a good job regardless - it's just html, css, and some scripts: https://web.archive.org/web/20201111230243/https://synthmata.com/volca-fm/

And I'm really happy that you like Synthmata!
